### ISSUE TITLE
Lumen IOC Dependancy Problem

### ISSUE THREAD

**Issue by linkthrow** [SammyK/LaravelFacebookSdk#135]
The constructor for the LaravelFacebookSdk required $url and $config which cannot be resolved

`Unresolvable dependency resolving [Parameter #2 [ <required> array $config ]] in class SammyK\\LaravelFacebookSdk\\LaravelFacebookSdk`

**Comment by linkthrow** [comment]
I have fixed it and made a pull request for this
https://github.com/SammyK/LaravelFacebookSdk/pull/136

**Comment by SammyK** [comment]
Hey @linkthrow! I'm not sure why you're getting this error as the dependencies are [resolved in the server provider](https://github.com/SammyK/LaravelFacebookSdk/blob/3.0/src/LaravelFacebookSdk/LaravelFacebookSdkServiceProvider.php#L49-L53). Are you using the package's service provider?

**Comment by SammyK** [comment]
Correction: I see what you're saying now. Let me dig into this a bit more.

**Comment by SammyK** [comment]
Ok - so I still don't know how you're getting this message if you're using the package's service provider. Did you [add the provider to your `bootstrap/app.php` file](https://github.com/SammyK/LaravelFacebookSdk#service-provider)?
